import { Circuit } from "@/domain/model/aggregate/circuit";
import { CircuitData } from "@/domain/model/valueObject/circuitData";
import { CircuitDescription } from "@/domain/model/valueObject/circuitDescription";
import { CircuitEdgeId } from "@/domain/model/valueObject/circuitEdgeId";
import { CircuitId } from "@/domain/model/valueObject/circuitId";
import { CircuitNodeId } from "@/domain/model/valueObject/circuitNodeId";
import { CircuitNodePinId } from "@/domain/model/valueObject/circuitNodePinId";
import { CircuitNodeSize } from "@/domain/model/valueObject/circuitNodeSize";
import { CircuitNodeType } from "@/domain/model/valueObject/circuitNodeType";
import { CircuitTitle } from "@/domain/model/valueObject/circuitTitle";
import { Coordinate } from "@/domain/model/valueObject/coordinate";
import { CreatedDateTime } from "@/domain/model/valueObject/createdDateTime";
import { UpdatedDateTime } from "@/domain/model/valueObject/updatedDateTime";

export const mockCircuitData: Array<Circuit> = [
  Circuit.from({
    id: CircuitId.from("sr-latch-circuit-01"),
    title: CircuitTitle.from("SRラッチ"),
    description: CircuitDescription.from(
      "【正しさが保証されているデータです】単純なSRラッチ回路です。セット(S)とリセット(R)の2つの入力を持ち、QとQ_の2つの出力を持ちます。",
    ),
    circuitData: CircuitData.from({
      nodes: [
        {
          id: CircuitNodeId.from("S"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("S_output0")],
          coordinate: Coordinate.from({ x: 50, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("R"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("R_output0")],
          coordinate: Coordinate.from({ x: 50, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT1"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT1_input0")],
          outputs: [CircuitNodePinId.from("NOT1_output0")],
          coordinate: Coordinate.from({ x: 150, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT2"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT2_input0")],
          outputs: [CircuitNodePinId.from("NOT2_output0")],
          coordinate: Coordinate.from({ x: 150, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("AND1"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("AND1_input0"), CircuitNodePinId.from("AND1_input1")],
          outputs: [CircuitNodePinId.from("AND1_output0")],
          coordinate: Coordinate.from({ x: 250, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT3"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT3_input0")],
          outputs: [CircuitNodePinId.from("NOT3_output0")],
          coordinate: Coordinate.from({ x: 350, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNCTION1"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNCTION1_input0")],
          outputs: [CircuitNodePinId.from("JUNCTION1_output0"), CircuitNodePinId.from("JUNCTION1_output1")],
          coordinate: Coordinate.from({ x: 450, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("AND2"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("AND2_input0"), CircuitNodePinId.from("AND2_input1")],
          outputs: [CircuitNodePinId.from("AND2_output0")],
          coordinate: Coordinate.from({ x: 250, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT4"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT4_input0")],
          outputs: [CircuitNodePinId.from("NOT4_output0")],
          coordinate: Coordinate.from({ x: 350, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNCTION2"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNCTION2_input0")],
          outputs: [CircuitNodePinId.from("JUNCTION2_output0"), CircuitNodePinId.from("JUNCTION2_output1")],
          coordinate: Coordinate.from({ x: 450, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Q"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("Q_input0")],
          outputs: [],
          coordinate: Coordinate.from({ x: 550, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Q_"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("Q__input0")],
          outputs: [],
          coordinate: Coordinate.from({ x: 550, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
      ],
      edges: [
        {
          id: CircuitEdgeId.from("edge_0"),
          from: CircuitNodePinId.from("S_output0"),
          to: CircuitNodePinId.from("NOT1_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_1"),
          from: CircuitNodePinId.from("R_output0"),
          to: CircuitNodePinId.from("NOT2_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_2"),
          from: CircuitNodePinId.from("NOT1_output0"),
          to: CircuitNodePinId.from("AND1_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_3"),
          from: CircuitNodePinId.from("NOT2_output0"),
          to: CircuitNodePinId.from("AND2_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_4"),
          from: CircuitNodePinId.from("JUNCTION2_output0"),
          to: CircuitNodePinId.from("AND1_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_5"),
          from: CircuitNodePinId.from("AND1_output0"),
          to: CircuitNodePinId.from("NOT3_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_6"),
          from: CircuitNodePinId.from("NOT3_output0"),
          to: CircuitNodePinId.from("JUNCTION1_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_7"),
          from: CircuitNodePinId.from("JUNCTION1_output0"),
          to: CircuitNodePinId.from("AND2_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_8"),
          from: CircuitNodePinId.from("JUNCTION1_output1"),
          to: CircuitNodePinId.from("Q_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_9"),
          from: CircuitNodePinId.from("AND2_output0"),
          to: CircuitNodePinId.from("NOT4_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_10"),
          from: CircuitNodePinId.from("NOT4_output0"),
          to: CircuitNodePinId.from("JUNCTION2_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_11"),
          from: CircuitNodePinId.from("JUNCTION2_output1"),
          to: CircuitNodePinId.from("Q__input0"),
          waypoints: null,
        },
      ],
    }),
    createdAt: CreatedDateTime.fromDate(new Date("2023-10-26T10:00:00Z")),
    updatedAt: UpdatedDateTime.fromDate(new Date("2023-10-26T11:30:00Z")),
  }),
  Circuit.from({
    id: CircuitId.from("full-adder-circuit-01"),
    title: CircuitTitle.from("全加算器"),
    description: CircuitDescription.from(
      "【正しさが保証されているデータです】3入力の全加算器です。入力としてM, S, Bを持ちます",
    ),
    circuitData: CircuitData.from({
      nodes: [
        {
          id: CircuitNodeId.from("A"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("A_output0")],
          coordinate: Coordinate.from({ x: 50, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("B"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("B_output0")],
          coordinate: Coordinate.from({ x: 50, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Cin"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("Cin_output0")],
          coordinate: Coordinate.from({ x: 50, y: 250 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNC_A"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNC_A_input0")],
          outputs: [
            CircuitNodePinId.from("JUNC_A_output0"),
            CircuitNodePinId.from("JUNC_A_output1"),
            CircuitNodePinId.from("JUNC_A_output2"),
          ],
          coordinate: Coordinate.from({ x: 100, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNC_B"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNC_B_input0")],
          outputs: [
            CircuitNodePinId.from("JUNC_B_output0"),
            CircuitNodePinId.from("JUNC_B_output1"),
            CircuitNodePinId.from("JUNC_B_output2"),
          ],
          coordinate: Coordinate.from({ x: 100, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNC_Cin"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNC_Cin_input0")],
          outputs: [
            CircuitNodePinId.from("JUNC_Cin_output0"),
            CircuitNodePinId.from("JUNC_Cin_output1"),
            CircuitNodePinId.from("JUNC_Cin_output2"),
          ],
          coordinate: Coordinate.from({ x: 100, y: 250 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_A"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT_A_input0")],
          outputs: [CircuitNodePinId.from("NOT_A_output0")],
          coordinate: Coordinate.from({ x: 150, y: 30 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_B"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT_B_input0")],
          outputs: [CircuitNodePinId.from("NOT_B_output0")],
          coordinate: Coordinate.from({ x: 150, y: 130 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_Cin"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT_Cin_input0")],
          outputs: [CircuitNodePinId.from("NOT_Cin_output0")],
          coordinate: Coordinate.from({ x: 150, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("A_AND_NOT_B"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("A_AND_NOT_B_input0"), CircuitNodePinId.from("A_AND_NOT_B_input1")],
          outputs: [CircuitNodePinId.from("A_AND_NOT_B_output0")],
          coordinate: Coordinate.from({ x: 250, y: 30 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_A_AND_B"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("NOT_A_AND_B_input0"), CircuitNodePinId.from("NOT_A_AND_B_input1")],
          outputs: [CircuitNodePinId.from("NOT_A_AND_B_output0")],
          coordinate: Coordinate.from({ x: 250, y: 130 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("A_XOR_B"),
          type: CircuitNodeType.from("OR"),
          inputs: [CircuitNodePinId.from("A_XOR_B_input0"), CircuitNodePinId.from("A_XOR_B_input1")],
          outputs: [CircuitNodePinId.from("A_XOR_B_output0")],
          coordinate: Coordinate.from({ x: 350, y: 80 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNC_AXORB"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNC_AXORB_input0")],
          outputs: [
            CircuitNodePinId.from("JUNC_AXORB_output0"),
            CircuitNodePinId.from("JUNC_AXORB_output1"),
            CircuitNodePinId.from("JUNC_AXORB_output2"),
          ],
          coordinate: Coordinate.from({ x: 400, y: 80 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_AXORB"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT_AXORB_input0")],
          outputs: [CircuitNodePinId.from("NOT_AXORB_output0")],
          coordinate: Coordinate.from({ x: 450, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("AXORB_AND_NOT_Cin"),
          type: CircuitNodeType.from("AND"),
          inputs: [
            CircuitNodePinId.from("AXORB_AND_NOT_Cin_input0"),
            CircuitNodePinId.from("AXORB_AND_NOT_Cin_input1"),
          ],
          outputs: [CircuitNodePinId.from("AXORB_AND_NOT_Cin_output0")],
          coordinate: Coordinate.from({ x: 550, y: 30 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_AXORB_AND_Cin"),
          type: CircuitNodeType.from("AND"),
          inputs: [
            CircuitNodePinId.from("NOT_AXORB_AND_Cin_input0"),
            CircuitNodePinId.from("NOT_AXORB_AND_Cin_input1"),
          ],
          outputs: [CircuitNodePinId.from("NOT_AXORB_AND_Cin_output0")],
          coordinate: Coordinate.from({ x: 550, y: 130 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("SUM"),
          type: CircuitNodeType.from("OR"),
          inputs: [CircuitNodePinId.from("SUM_input0"), CircuitNodePinId.from("SUM_input1")],
          outputs: [CircuitNodePinId.from("SUM_output0")],
          coordinate: Coordinate.from({ x: 650, y: 80 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("A_AND_B"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("A_AND_B_input0"), CircuitNodePinId.from("A_AND_B_input1")],
          outputs: [CircuitNodePinId.from("A_AND_B_output0")],
          coordinate: Coordinate.from({ x: 250, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Cin_AND_AXORB"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("Cin_AND_AXORB_input0"), CircuitNodePinId.from("Cin_AND_AXORB_input1")],
          outputs: [CircuitNodePinId.from("Cin_AND_AXORB_output0")],
          coordinate: Coordinate.from({ x: 450, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Curry"),
          type: CircuitNodeType.from("OR"),
          inputs: [CircuitNodePinId.from("Curry_input0"), CircuitNodePinId.from("Curry_input1")],
          outputs: [CircuitNodePinId.from("Curry_output0")],
          coordinate: Coordinate.from({ x: 550, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("SumOut"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("SumOut_input0")],
          outputs: [],
          coordinate: Coordinate.from({ x: 750, y: 80 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("CurryOut"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("CurryOut_input0")],
          outputs: [],
          coordinate: Coordinate.from({ x: 650, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
      ],
      edges: [
        {
          id: CircuitEdgeId.from("e0"),
          from: CircuitNodePinId.from("A_output0"),
          to: CircuitNodePinId.from("JUNC_A_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e1"),
          from: CircuitNodePinId.from("JUNC_A_output0"),
          to: CircuitNodePinId.from("NOT_A_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e2"),
          from: CircuitNodePinId.from("JUNC_A_output1"),
          to: CircuitNodePinId.from("A_AND_NOT_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e3"),
          from: CircuitNodePinId.from("JUNC_A_output2"),
          to: CircuitNodePinId.from("A_AND_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e4"),
          from: CircuitNodePinId.from("B_output0"),
          to: CircuitNodePinId.from("JUNC_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e5"),
          from: CircuitNodePinId.from("JUNC_B_output0"),
          to: CircuitNodePinId.from("NOT_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e6"),
          from: CircuitNodePinId.from("JUNC_B_output1"),
          to: CircuitNodePinId.from("NOT_A_AND_B_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e7"),
          from: CircuitNodePinId.from("JUNC_B_output2"),
          to: CircuitNodePinId.from("A_AND_B_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e8"),
          from: CircuitNodePinId.from("Cin_output0"),
          to: CircuitNodePinId.from("JUNC_Cin_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e9"),
          from: CircuitNodePinId.from("JUNC_Cin_output0"),
          to: CircuitNodePinId.from("NOT_Cin_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e10"),
          from: CircuitNodePinId.from("JUNC_Cin_output1"),
          to: CircuitNodePinId.from("NOT_AXORB_AND_Cin_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e11"),
          from: CircuitNodePinId.from("JUNC_Cin_output2"),
          to: CircuitNodePinId.from("Cin_AND_AXORB_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e12"),
          from: CircuitNodePinId.from("NOT_A_output0"),
          to: CircuitNodePinId.from("NOT_A_AND_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e13"),
          from: CircuitNodePinId.from("NOT_B_output0"),
          to: CircuitNodePinId.from("A_AND_NOT_B_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e14"),
          from: CircuitNodePinId.from("A_AND_NOT_B_output0"),
          to: CircuitNodePinId.from("A_XOR_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e15"),
          from: CircuitNodePinId.from("NOT_A_AND_B_output0"),
          to: CircuitNodePinId.from("A_XOR_B_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e16"),
          from: CircuitNodePinId.from("A_XOR_B_output0"),
          to: CircuitNodePinId.from("JUNC_AXORB_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e17"),
          from: CircuitNodePinId.from("JUNC_AXORB_output0"),
          to: CircuitNodePinId.from("NOT_AXORB_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e18"),
          from: CircuitNodePinId.from("JUNC_AXORB_output1"),
          to: CircuitNodePinId.from("AXORB_AND_NOT_Cin_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e19"),
          from: CircuitNodePinId.from("JUNC_AXORB_output2"),
          to: CircuitNodePinId.from("Cin_AND_AXORB_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e20"),
          from: CircuitNodePinId.from("NOT_Cin_output0"),
          to: CircuitNodePinId.from("AXORB_AND_NOT_Cin_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e21"),
          from: CircuitNodePinId.from("NOT_AXORB_output0"),
          to: CircuitNodePinId.from("NOT_AXORB_AND_Cin_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e22"),
          from: CircuitNodePinId.from("AXORB_AND_NOT_Cin_output0"),
          to: CircuitNodePinId.from("SUM_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e23"),
          from: CircuitNodePinId.from("NOT_AXORB_AND_Cin_output0"),
          to: CircuitNodePinId.from("SUM_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e24"),
          from: CircuitNodePinId.from("SUM_output0"),
          to: CircuitNodePinId.from("SumOut_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e25"),
          from: CircuitNodePinId.from("A_AND_B_output0"),
          to: CircuitNodePinId.from("Curry_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e26"),
          from: CircuitNodePinId.from("Cin_AND_AXORB_output0"),
          to: CircuitNodePinId.from("Curry_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e27"),
          from: CircuitNodePinId.from("Curry_output0"),
          to: CircuitNodePinId.from("CurryOut_input0"),
          waypoints: null,
        },
      ],
    }),

    createdAt: CreatedDateTime.fromDate(new Date("2023-10-26T10:00:00Z")),
    updatedAt: UpdatedDateTime.fromDate(new Date("2023-10-26T12:00:00Z")),
  }),
];
