import { Circuit } from "@/domain/model/aggregate/circuit";
import { CircuitData } from "@/domain/model/valueObject/circuitData";
import { CircuitDescription } from "@/domain/model/valueObject/circuitDescription";
import { CircuitEdgeId } from "@/domain/model/valueObject/circuitEdgeId";
import { CircuitId } from "@/domain/model/valueObject/circuitId";
import { CircuitNodeId } from "@/domain/model/valueObject/circuitNodeId";
import { CircuitNodePinId } from "@/domain/model/valueObject/circuitNodePinId";
import { CircuitNodeSize } from "@/domain/model/valueObject/circuitNodeSize";
import { CircuitNodeType } from "@/domain/model/valueObject/circuitNodeType";
import { CircuitTitle } from "@/domain/model/valueObject/circuitTitle";
import { Coordinate } from "@/domain/model/valueObject/coordinate";
import { CreatedDateTime } from "@/domain/model/valueObject/createdDateTime";
import { UpdatedDateTime } from "@/domain/model/valueObject/updatedDateTime";
import { Waypoint } from "@/domain/model/valueObject/waypoint";

export const mockCircuitData: Array<Circuit> = [
  Circuit.from({
    id: CircuitId.from("sr-latch-circuit-01"),
    title: CircuitTitle.from("SRラッチ"),
    description: CircuitDescription.from(
      "【正しさが保証されているデータです】単純なSRラッチ回路です。セット(S)とリセット(R)の2つの入力を持ち、QとQ_の2つの出力を持ちます。",
    ),
    circuitData: CircuitData.from({
      nodes: [
        {
          id: CircuitNodeId.from("S"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("S_output0")],
          coordinate: Coordinate.from({ x: 50, y: 44 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("R"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("R_output0")],
          coordinate: Coordinate.from({ x: 50, y: 156 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT1"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT1_input0")],
          outputs: [CircuitNodePinId.from("NOT1_output0")],
          coordinate: Coordinate.from({ x: 150, y: 44 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT2"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT2_input0")],
          outputs: [CircuitNodePinId.from("NOT2_output0")],
          coordinate: Coordinate.from({ x: 150, y: 156 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("AND1"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("AND1_input0"), CircuitNodePinId.from("AND1_input1")],
          outputs: [CircuitNodePinId.from("AND1_output0")],
          coordinate: Coordinate.from({ x: 250, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT3"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT3_input0")],
          outputs: [CircuitNodePinId.from("NOT3_output0")],
          coordinate: Coordinate.from({ x: 350, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNCTION1"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNCTION1_input0")],
          outputs: [CircuitNodePinId.from("JUNCTION1_output0"), CircuitNodePinId.from("JUNCTION1_output1")],
          coordinate: Coordinate.from({ x: 450, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("AND2"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("AND2_input0"), CircuitNodePinId.from("AND2_input1")],
          outputs: [CircuitNodePinId.from("AND2_output0")],
          coordinate: Coordinate.from({ x: 250, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT4"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT4_input0")],
          outputs: [CircuitNodePinId.from("NOT4_output0")],
          coordinate: Coordinate.from({ x: 350, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNCTION2"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNCTION2_input0")],
          outputs: [CircuitNodePinId.from("JUNCTION2_output0"), CircuitNodePinId.from("JUNCTION2_output1")],
          coordinate: Coordinate.from({ x: 450, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Q"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("Q_input0")],
          outputs: [],
          coordinate: Coordinate.from({ x: 550, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Q_"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("Q__input0")],
          outputs: [],
          coordinate: Coordinate.from({ x: 550, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
      ],
      edges: [
        {
          id: CircuitEdgeId.from("edge_0"),
          from: CircuitNodePinId.from("S_output0"),
          to: CircuitNodePinId.from("NOT1_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_1"),
          from: CircuitNodePinId.from("R_output0"),
          to: CircuitNodePinId.from("NOT2_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_2"),
          from: CircuitNodePinId.from("NOT1_output0"),
          to: CircuitNodePinId.from("AND1_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_3"),
          from: CircuitNodePinId.from("NOT2_output0"),
          to: CircuitNodePinId.from("AND2_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_4"),
          from: CircuitNodePinId.from("JUNCTION2_output0"),
          to: CircuitNodePinId.from("AND1_input1"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: 450, y: 150 }),
            Coordinate.from({ x: 450, y: 125 }),
            Coordinate.from({ x: 200, y: 75 }),
            Coordinate.from({ x: 200, y: 57 }),
          ]),
        },
        {
          id: CircuitEdgeId.from("edge_5"),
          from: CircuitNodePinId.from("AND1_output0"),
          to: CircuitNodePinId.from("NOT3_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_6"),
          from: CircuitNodePinId.from("NOT3_output0"),
          to: CircuitNodePinId.from("JUNCTION1_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_7"),
          from: CircuitNodePinId.from("JUNCTION1_output0"),
          to: CircuitNodePinId.from("AND2_input0"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: 450, y: 50 }),
            Coordinate.from({ x: 450, y: 75 }),
            Coordinate.from({ x: 200, y: 125 }),
            Coordinate.from({ x: 200, y: 143 }),
          ]),
        },
        {
          id: CircuitEdgeId.from("edge_8"),
          from: CircuitNodePinId.from("JUNCTION1_output1"),
          to: CircuitNodePinId.from("Q_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_9"),
          from: CircuitNodePinId.from("AND2_output0"),
          to: CircuitNodePinId.from("NOT4_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_10"),
          from: CircuitNodePinId.from("NOT4_output0"),
          to: CircuitNodePinId.from("JUNCTION2_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge_11"),
          from: CircuitNodePinId.from("JUNCTION2_output1"),
          to: CircuitNodePinId.from("Q__input0"),
          waypoints: null,
        },
      ],
    }),
    createdAt: CreatedDateTime.fromDate(new Date("2023-10-26T10:00:00Z")),
    updatedAt: UpdatedDateTime.fromDate(new Date("2023-10-26T11:30:00Z")),
  }),
  Circuit.from({
    id: CircuitId.from("full-adder-circuit-01"),
    title: CircuitTitle.from("全加算器"),
    description: CircuitDescription.from(
      "【正しさが保証されているデータです】3入力の全加算器です。入力としてM, S, Bを持ちます",
    ),
    circuitData: CircuitData.from({
      nodes: [
        {
          id: CircuitNodeId.from("A"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("A_output0")],
          coordinate: Coordinate.from({ x: 50, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("B"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("B_output0")],
          coordinate: Coordinate.from({ x: 50, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Cin"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("Cin_output0")],
          coordinate: Coordinate.from({ x: 50, y: 250 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNC_A"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNC_A_input0")],
          outputs: [
            CircuitNodePinId.from("JUNC_A_output0"),
            CircuitNodePinId.from("JUNC_A_output1"),
            CircuitNodePinId.from("JUNC_A_output2"),
          ],
          coordinate: Coordinate.from({ x: 100, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNC_B"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNC_B_input0")],
          outputs: [
            CircuitNodePinId.from("JUNC_B_output0"),
            CircuitNodePinId.from("JUNC_B_output1"),
            CircuitNodePinId.from("JUNC_B_output2"),
          ],
          coordinate: Coordinate.from({ x: 100, y: 150 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNC_Cin"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNC_Cin_input0")],
          outputs: [
            CircuitNodePinId.from("JUNC_Cin_output0"),
            CircuitNodePinId.from("JUNC_Cin_output1"),
            CircuitNodePinId.from("JUNC_Cin_output2"),
          ],
          coordinate: Coordinate.from({ x: 100, y: 250 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_A"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT_A_input0")],
          outputs: [CircuitNodePinId.from("NOT_A_output0")],
          coordinate: Coordinate.from({ x: 150, y: 30 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_B"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT_B_input0")],
          outputs: [CircuitNodePinId.from("NOT_B_output0")],
          coordinate: Coordinate.from({ x: 150, y: 130 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_Cin"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT_Cin_input0")],
          outputs: [CircuitNodePinId.from("NOT_Cin_output0")],
          coordinate: Coordinate.from({ x: 150, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("A_AND_NOT_B"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("A_AND_NOT_B_input0"), CircuitNodePinId.from("A_AND_NOT_B_input1")],
          outputs: [CircuitNodePinId.from("A_AND_NOT_B_output0")],
          coordinate: Coordinate.from({ x: 250, y: 30 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_A_AND_B"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("NOT_A_AND_B_input0"), CircuitNodePinId.from("NOT_A_AND_B_input1")],
          outputs: [CircuitNodePinId.from("NOT_A_AND_B_output0")],
          coordinate: Coordinate.from({ x: 250, y: 130 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("A_XOR_B"),
          type: CircuitNodeType.from("OR"),
          inputs: [CircuitNodePinId.from("A_XOR_B_input0"), CircuitNodePinId.from("A_XOR_B_input1")],
          outputs: [CircuitNodePinId.from("A_XOR_B_output0")],
          coordinate: Coordinate.from({ x: 350, y: 80 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("JUNC_AXORB"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("JUNC_AXORB_input0")],
          outputs: [
            CircuitNodePinId.from("JUNC_AXORB_output0"),
            CircuitNodePinId.from("JUNC_AXORB_output1"),
            CircuitNodePinId.from("JUNC_AXORB_output2"),
          ],
          coordinate: Coordinate.from({ x: 400, y: 80 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_AXORB"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("NOT_AXORB_input0")],
          outputs: [CircuitNodePinId.from("NOT_AXORB_output0")],
          coordinate: Coordinate.from({ x: 450, y: 50 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("AXORB_AND_NOT_Cin"),
          type: CircuitNodeType.from("AND"),
          inputs: [
            CircuitNodePinId.from("AXORB_AND_NOT_Cin_input0"),
            CircuitNodePinId.from("AXORB_AND_NOT_Cin_input1"),
          ],
          outputs: [CircuitNodePinId.from("AXORB_AND_NOT_Cin_output0")],
          coordinate: Coordinate.from({ x: 550, y: 30 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("NOT_AXORB_AND_Cin"),
          type: CircuitNodeType.from("AND"),
          inputs: [
            CircuitNodePinId.from("NOT_AXORB_AND_Cin_input0"),
            CircuitNodePinId.from("NOT_AXORB_AND_Cin_input1"),
          ],
          outputs: [CircuitNodePinId.from("NOT_AXORB_AND_Cin_output0")],
          coordinate: Coordinate.from({ x: 550, y: 130 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("SUM"),
          type: CircuitNodeType.from("OR"),
          inputs: [CircuitNodePinId.from("SUM_input0"), CircuitNodePinId.from("SUM_input1")],
          outputs: [CircuitNodePinId.from("SUM_output0")],
          coordinate: Coordinate.from({ x: 650, y: 80 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("A_AND_B"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("A_AND_B_input0"), CircuitNodePinId.from("A_AND_B_input1")],
          outputs: [CircuitNodePinId.from("A_AND_B_output0")],
          coordinate: Coordinate.from({ x: 250, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Cin_AND_AXORB"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("Cin_AND_AXORB_input0"), CircuitNodePinId.from("Cin_AND_AXORB_input1")],
          outputs: [CircuitNodePinId.from("Cin_AND_AXORB_output0")],
          coordinate: Coordinate.from({ x: 450, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("Curry"),
          type: CircuitNodeType.from("OR"),
          inputs: [CircuitNodePinId.from("Curry_input0"), CircuitNodePinId.from("Curry_input1")],
          outputs: [CircuitNodePinId.from("Curry_output0")],
          coordinate: Coordinate.from({ x: 550, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("SumOut"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("SumOut_input0")],
          outputs: [],
          coordinate: Coordinate.from({ x: 750, y: 80 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("CurryOut"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("CurryOut_input0")],
          outputs: [],
          coordinate: Coordinate.from({ x: 650, y: 230 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
      ],
      edges: [
        {
          id: CircuitEdgeId.from("e0"),
          from: CircuitNodePinId.from("A_output0"),
          to: CircuitNodePinId.from("JUNC_A_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e1"),
          from: CircuitNodePinId.from("JUNC_A_output0"),
          to: CircuitNodePinId.from("NOT_A_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e2"),
          from: CircuitNodePinId.from("JUNC_A_output1"),
          to: CircuitNodePinId.from("A_AND_NOT_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e3"),
          from: CircuitNodePinId.from("JUNC_A_output2"),
          to: CircuitNodePinId.from("A_AND_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e4"),
          from: CircuitNodePinId.from("B_output0"),
          to: CircuitNodePinId.from("JUNC_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e5"),
          from: CircuitNodePinId.from("JUNC_B_output0"),
          to: CircuitNodePinId.from("NOT_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e6"),
          from: CircuitNodePinId.from("JUNC_B_output1"),
          to: CircuitNodePinId.from("NOT_A_AND_B_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e7"),
          from: CircuitNodePinId.from("JUNC_B_output2"),
          to: CircuitNodePinId.from("A_AND_B_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e8"),
          from: CircuitNodePinId.from("Cin_output0"),
          to: CircuitNodePinId.from("JUNC_Cin_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e9"),
          from: CircuitNodePinId.from("JUNC_Cin_output0"),
          to: CircuitNodePinId.from("NOT_Cin_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e10"),
          from: CircuitNodePinId.from("JUNC_Cin_output1"),
          to: CircuitNodePinId.from("NOT_AXORB_AND_Cin_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e11"),
          from: CircuitNodePinId.from("JUNC_Cin_output2"),
          to: CircuitNodePinId.from("Cin_AND_AXORB_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e12"),
          from: CircuitNodePinId.from("NOT_A_output0"),
          to: CircuitNodePinId.from("NOT_A_AND_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e13"),
          from: CircuitNodePinId.from("NOT_B_output0"),
          to: CircuitNodePinId.from("A_AND_NOT_B_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e14"),
          from: CircuitNodePinId.from("A_AND_NOT_B_output0"),
          to: CircuitNodePinId.from("A_XOR_B_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e15"),
          from: CircuitNodePinId.from("NOT_A_AND_B_output0"),
          to: CircuitNodePinId.from("A_XOR_B_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e16"),
          from: CircuitNodePinId.from("A_XOR_B_output0"),
          to: CircuitNodePinId.from("JUNC_AXORB_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e17"),
          from: CircuitNodePinId.from("JUNC_AXORB_output0"),
          to: CircuitNodePinId.from("NOT_AXORB_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e18"),
          from: CircuitNodePinId.from("JUNC_AXORB_output1"),
          to: CircuitNodePinId.from("AXORB_AND_NOT_Cin_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e19"),
          from: CircuitNodePinId.from("JUNC_AXORB_output2"),
          to: CircuitNodePinId.from("Cin_AND_AXORB_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e20"),
          from: CircuitNodePinId.from("NOT_Cin_output0"),
          to: CircuitNodePinId.from("AXORB_AND_NOT_Cin_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e21"),
          from: CircuitNodePinId.from("NOT_AXORB_output0"),
          to: CircuitNodePinId.from("NOT_AXORB_AND_Cin_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e22"),
          from: CircuitNodePinId.from("AXORB_AND_NOT_Cin_output0"),
          to: CircuitNodePinId.from("SUM_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e23"),
          from: CircuitNodePinId.from("NOT_AXORB_AND_Cin_output0"),
          to: CircuitNodePinId.from("SUM_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e24"),
          from: CircuitNodePinId.from("SUM_output0"),
          to: CircuitNodePinId.from("SumOut_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e25"),
          from: CircuitNodePinId.from("A_AND_B_output0"),
          to: CircuitNodePinId.from("Curry_input0"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e26"),
          from: CircuitNodePinId.from("Cin_AND_AXORB_output0"),
          to: CircuitNodePinId.from("Curry_input1"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("e27"),
          from: CircuitNodePinId.from("Curry_output0"),
          to: CircuitNodePinId.from("CurryOut_input0"),
          waypoints: null,
        },
      ],
    }),
    createdAt: CreatedDateTime.fromDate(new Date("2023-10-26T10:00:00Z")),
    updatedAt: UpdatedDateTime.fromDate(new Date("2023-10-26T12:00:00Z")),
  }),
  Circuit.from({
    id: CircuitId.from("circuit-0d22e9ad4957d8"),
    title: CircuitTitle.from("Dフリップフロップ"),
    description: CircuitDescription.from("ゲートを持つDフリップフロップです。"),
    circuitData: CircuitData.from({
      nodes: [
        {
          id: CircuitNodeId.from("node-6102683f6b011"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("pin-d6ab37751701d8")],
          coordinate: Coordinate.from({ x: -460, y: -38 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-cc6148f79098b8"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("pin-32c1225016a108"), CircuitNodePinId.from("pin-2d9493a6690cb8")],
          outputs: [CircuitNodePinId.from("pin-9a976f0b85a2b8")],
          coordinate: Coordinate.from({ x: -348, y: -31 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-f789b3fd1a322"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("pin-96fd12f2a44f8")],
          outputs: [CircuitNodePinId.from("pin-e725e90ca2f138")],
          coordinate: Coordinate.from({ x: -233, y: -32 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-17cfa0bdc18d6"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("pin-f451749b2846f8"), CircuitNodePinId.from("pin-33e59ba0f67ce8")],
          outputs: [CircuitNodePinId.from("pin-220819cb792a48")],
          coordinate: Coordinate.from({ x: -69, y: -25 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-d79dc78ce09a3"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("pin-db062a5d271dc8")],
          outputs: [CircuitNodePinId.from("pin-dc1ac7a102581")],
          coordinate: Coordinate.from({ x: -149, y: -32 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-994f0f72fa736"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("pin-fabba3838fa52")],
          outputs: [CircuitNodePinId.from("pin-e3960f00c52468")],
          coordinate: Coordinate.from({ x: 92, y: -25 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-02732a36bd143"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("pin-3e23d9bf8d18f")],
          outputs: [CircuitNodePinId.from("pin-990a3b4ab5adc8")],
          coordinate: Coordinate.from({ x: 20, y: -25 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-cddfda195a7bb8"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("pin-aecae84af5c0e8"), CircuitNodePinId.from("pin-99d13ff5887808")],
          outputs: [CircuitNodePinId.from("pin-66f972a3c57d68")],
          coordinate: Coordinate.from({ x: -183, y: 84 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-fc7fa60e7c83d8"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("pin-0d83d4d8895598")],
          outputs: [CircuitNodePinId.from("pin-4b82d174fdb6b8")],
          coordinate: Coordinate.from({ x: -84, y: 84 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-c43a4f1230b4e8"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("pin-837b6083c358d8"), CircuitNodePinId.from("pin-7f355270e8bcc")],
          outputs: [CircuitNodePinId.from("pin-c077a67873d56")],
          coordinate: Coordinate.from({ x: 20, y: 77 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-a1ef124d4a74e"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("pin-23722d8b4102e8")],
          outputs: [CircuitNodePinId.from("pin-9468a02debbd58")],
          coordinate: Coordinate.from({ x: -330, y: 90 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-5573e4d85a427"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("pin-3b9e52b75b6a3")],
          outputs: [CircuitNodePinId.from("pin-3aaedaa886b778")],
          coordinate: Coordinate.from({ x: -260, y: 90 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-324da73790d168"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("pin-a8cd029c91e3")],
          outputs: [CircuitNodePinId.from("pin-608521f40b9268")],
          coordinate: Coordinate.from({ x: 121, y: 77 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-cf49ceb0249798"),
          type: CircuitNodeType.from("ENTRY"),
          inputs: [],
          outputs: [CircuitNodePinId.from("pin-7502be86fbd6e")],
          coordinate: Coordinate.from({ x: -460, y: 90 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-cc6e0bef56c528"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("pin-80ed95516bb3f8")],
          outputs: [CircuitNodePinId.from("pin-38d986e8b47c68")],
          coordinate: Coordinate.from({ x: -400, y: 90 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-6804905d1a645"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("pin-40a5466725ba88"), CircuitNodePinId.from("pin-9aaa9b6416b238")],
          outputs: [CircuitNodePinId.from("pin-1980ef871ebf48")],
          coordinate: Coordinate.from({ x: -331, y: 156 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-1390c335f83408"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("pin-512d1fa4a3de18"), CircuitNodePinId.from("pin-ad739ddf9cc008")],
          outputs: [CircuitNodePinId.from("pin-798ddf0ba646e8")],
          coordinate: Coordinate.from({ x: -329, y: 260 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-1236fe0910ae6"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("pin-03615efcc9c608")],
          outputs: [CircuitNodePinId.from("pin-1181e001ac90b8")],
          coordinate: Coordinate.from({ x: -230, y: 156 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-503cc285b8ea18"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("pin-3429f4eb29ed48")],
          outputs: [CircuitNodePinId.from("pin-e9a8231b7a4ee")],
          coordinate: Coordinate.from({ x: -230, y: 260 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-336b9400f9aff8"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("pin-00b80bf24989d"), CircuitNodePinId.from("pin-604992a7342978")],
          outputs: [CircuitNodePinId.from("pin-4c18c659d2ded8")],
          coordinate: Coordinate.from({ x: -91, y: 254 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-a01da90eba58c"),
          type: CircuitNodeType.from("AND"),
          inputs: [CircuitNodePinId.from("pin-06e2159b4f132"), CircuitNodePinId.from("pin-84b172449d3b58")],
          outputs: [CircuitNodePinId.from("pin-3f0b297ab01f58")],
          coordinate: Coordinate.from({ x: -92, y: 162 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-c6894afa669828"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("pin-3cdfe98abbedf")],
          outputs: [CircuitNodePinId.from("pin-ae2e4ca8f125f8")],
          coordinate: Coordinate.from({ x: -163, y: 156 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-7d4dbc1275cd38"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("pin-d4c82764a3d508")],
          outputs: [CircuitNodePinId.from("pin-73a25248ddf928")],
          coordinate: Coordinate.from({ x: 20, y: 254 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-80377c9020f15"),
          type: CircuitNodeType.from("NOT"),
          inputs: [CircuitNodePinId.from("pin-f655f00b814e7")],
          outputs: [CircuitNodePinId.from("pin-98c9b3dd56089")],
          coordinate: Coordinate.from({ x: 20, y: 162 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-5af387e27074a"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("pin-efc640e18fdde")],
          outputs: [CircuitNodePinId.from("pin-6356e9acc6e818")],
          coordinate: Coordinate.from({ x: 100, y: 254 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-5b022faf25816"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("pin-6aba24a5ddfd3")],
          outputs: [CircuitNodePinId.from("pin-0206da677d935")],
          coordinate: Coordinate.from({ x: 100, y: 162 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-2c6c1e24c181"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("pin-33f483626eb8a8")],
          outputs: [],
          coordinate: Coordinate.from({ x: 165, y: 162 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-c3687fb9e1da78"),
          type: CircuitNodeType.from("EXIT"),
          inputs: [CircuitNodePinId.from("pin-4eb6137c552fb")],
          outputs: [],
          coordinate: Coordinate.from({ x: 160, y: 254 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
        {
          id: CircuitNodeId.from("node-5b59d048763b78"),
          type: CircuitNodeType.from("JUNCTION"),
          inputs: [CircuitNodePinId.from("pin-9cc84857683188")],
          outputs: [CircuitNodePinId.from("pin-1d338bb544e088")],
          coordinate: Coordinate.from({ x: -400, y: 163 }),
          size: CircuitNodeSize.from({ x: 60, y: 40 }),
        },
      ],
      edges: [
        {
          id: CircuitEdgeId.from("edge-1826f127270978"),
          from: CircuitNodePinId.from("pin-d6ab37751701d8"),
          to: CircuitNodePinId.from("pin-32c1225016a108"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-ae0aabbfa4d128"),
          from: CircuitNodePinId.from("pin-9a976f0b85a2b8"),
          to: CircuitNodePinId.from("pin-96fd12f2a44f8"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-8201450a3b5698"),
          from: CircuitNodePinId.from("pin-e725e90ca2f138"),
          to: CircuitNodePinId.from("pin-db062a5d271dc8"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-a23363f8519cf8"),
          from: CircuitNodePinId.from("pin-dc1ac7a102581"),
          to: CircuitNodePinId.from("pin-f451749b2846f8"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-0bdcfd59ea9838"),
          from: CircuitNodePinId.from("pin-220819cb792a48"),
          to: CircuitNodePinId.from("pin-3e23d9bf8d18f"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-f0b4924371a67"),
          from: CircuitNodePinId.from("pin-990a3b4ab5adc8"),
          to: CircuitNodePinId.from("pin-fabba3838fa52"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-9db8e8c521b438"),
          from: CircuitNodePinId.from("pin-dc1ac7a102581"),
          to: CircuitNodePinId.from("pin-aecae84af5c0e8"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: -149, y: -2 }),
            Coordinate.from({ x: -245, y: 50 }),
            Coordinate.from({ x: -245, y: 77 }),
          ]),
        },
        {
          id: CircuitEdgeId.from("edge-06a0e281438878"),
          from: CircuitNodePinId.from("pin-66f972a3c57d68"),
          to: CircuitNodePinId.from("pin-0d83d4d8895598"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-473dcdf0feccd"),
          from: CircuitNodePinId.from("pin-4b82d174fdb6b8"),
          to: CircuitNodePinId.from("pin-7f355270e8bcc"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-9acbdf37f6af78"),
          from: CircuitNodePinId.from("pin-9468a02debbd58"),
          to: CircuitNodePinId.from("pin-3b9e52b75b6a3"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-53b71064cb7e6"),
          from: CircuitNodePinId.from("pin-3aaedaa886b778"),
          to: CircuitNodePinId.from("pin-99d13ff5887808"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-da75e8e5b7d8e8"),
          from: CircuitNodePinId.from("pin-3aaedaa886b778"),
          to: CircuitNodePinId.from("pin-2d9493a6690cb8"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: -260, y: 60 }),
            Coordinate.from({ x: -400, y: 6 }),
            Coordinate.from({ x: -400, y: -24 }),
          ]),
        },
        {
          id: CircuitEdgeId.from("edge-b4140ef8b89358"),
          from: CircuitNodePinId.from("pin-c077a67873d56"),
          to: CircuitNodePinId.from("pin-a8cd029c91e3"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-f93680487848c"),
          from: CircuitNodePinId.from("pin-608521f40b9268"),
          to: CircuitNodePinId.from("pin-33e59ba0f67ce8"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: 151, y: 46 }),
            Coordinate.from({ x: -130, y: 12 }),
            Coordinate.from({ x: -130, y: -18 }),
          ]),
        },
        {
          id: CircuitEdgeId.from("edge-5dbab3cb1df8c8"),
          from: CircuitNodePinId.from("pin-7502be86fbd6e"),
          to: CircuitNodePinId.from("pin-80ed95516bb3f8"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-1b3332fca06af"),
          from: CircuitNodePinId.from("pin-38d986e8b47c68"),
          to: CircuitNodePinId.from("pin-23722d8b4102e8"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-de092e07112e18"),
          from: CircuitNodePinId.from("pin-798ddf0ba646e8"),
          to: CircuitNodePinId.from("pin-3429f4eb29ed48"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-f9e07d9c82d6c8"),
          from: CircuitNodePinId.from("pin-1980ef871ebf48"),
          to: CircuitNodePinId.from("pin-03615efcc9c608"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-45531daf45e3b8"),
          from: CircuitNodePinId.from("pin-1181e001ac90b8"),
          to: CircuitNodePinId.from("pin-3cdfe98abbedf"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-faf9ce2309d51"),
          from: CircuitNodePinId.from("pin-ae2e4ca8f125f8"),
          to: CircuitNodePinId.from("pin-06e2159b4f132"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-6e398e014bf578"),
          from: CircuitNodePinId.from("pin-4c18c659d2ded8"),
          to: CircuitNodePinId.from("pin-d4c82764a3d508"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-c5f266660441b"),
          from: CircuitNodePinId.from("pin-3f0b297ab01f58"),
          to: CircuitNodePinId.from("pin-f655f00b814e7"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-90a341f03f16d8"),
          from: CircuitNodePinId.from("pin-73a25248ddf928"),
          to: CircuitNodePinId.from("pin-efc640e18fdde"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-aeaf807814a53"),
          from: CircuitNodePinId.from("pin-98c9b3dd56089"),
          to: CircuitNodePinId.from("pin-6aba24a5ddfd3"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-f44c9cf3256d9"),
          from: CircuitNodePinId.from("pin-0206da677d935"),
          to: CircuitNodePinId.from("pin-33f483626eb8a8"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-7ab85380850298"),
          from: CircuitNodePinId.from("pin-6356e9acc6e818"),
          to: CircuitNodePinId.from("pin-4eb6137c552fb"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-96c4f03060f048"),
          from: CircuitNodePinId.from("pin-0206da677d935"),
          to: CircuitNodePinId.from("pin-00b80bf24989d"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: 100, y: 190 }),
            Coordinate.from({ x: -150, y: 217 }),
            Coordinate.from({ x: -150, y: 247 }),
          ]),
        },
        {
          id: CircuitEdgeId.from("edge-e974580a111b4"),
          from: CircuitNodePinId.from("pin-6356e9acc6e818"),
          to: CircuitNodePinId.from("pin-84b172449d3b58"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: 100, y: 225 }),
            Coordinate.from({ x: -150, y: 198 }),
            Coordinate.from({ x: -150, y: 169 }),
          ]),
        },
        {
          id: CircuitEdgeId.from("edge-dcc2df46e49138"),
          from: CircuitNodePinId.from("pin-ae2e4ca8f125f8"),
          to: CircuitNodePinId.from("pin-512d1fa4a3de18"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: -163, y: 184 }),
            Coordinate.from({ x: -385, y: 222 }),
            Coordinate.from({ x: -385, y: 253 }),
          ]),
        },
        {
          id: CircuitEdgeId.from("edge-9f36eb5500ede8"),
          from: CircuitNodePinId.from("pin-e9a8231b7a4ee"),
          to: CircuitNodePinId.from("pin-604992a7342978"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-e24c9cc76e3fb8"),
          from: CircuitNodePinId.from("pin-1d338bb544e088"),
          to: CircuitNodePinId.from("pin-9aaa9b6416b238"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-251269b4da028"),
          from: CircuitNodePinId.from("pin-38d986e8b47c68"),
          to: CircuitNodePinId.from("pin-9cc84857683188"),
          waypoints: null,
        },
        {
          id: CircuitEdgeId.from("edge-cebb7013cbcd88"),
          from: CircuitNodePinId.from("pin-1d338bb544e088"),
          to: CircuitNodePinId.from("pin-ad739ddf9cc008"),
          waypoints: Waypoint.coordinatesToWaypoints([Coordinate.from({ x: -400, y: 267 })]),
        },
        {
          id: CircuitEdgeId.from("edge-0864f5c79b3308"),
          from: CircuitNodePinId.from("pin-e3960f00c52468"),
          to: CircuitNodePinId.from("pin-837b6083c358d8"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: 93, y: 12 }),
            Coordinate.from({ x: -40, y: 40 }),
            Coordinate.from({ x: -40, y: 70 }),
          ]),
        },
        {
          id: CircuitEdgeId.from("edge-51d9e92e0c1f28"),
          from: CircuitNodePinId.from("pin-e3960f00c52468"),
          to: CircuitNodePinId.from("pin-40a5466725ba88"),
          waypoints: Waypoint.coordinatesToWaypoints([
            Coordinate.from({ x: 170, y: -25 }),
            Coordinate.from({ x: 170, y: 120 }),
            Coordinate.from({ x: -385, y: 120 }),
            Coordinate.from({ x: -385, y: 150 }),
          ]),
        },
      ],
    }),
    createdAt: CreatedDateTime.fromDate(new Date("2025-08-26T07:48:31.768Z")),
    updatedAt: UpdatedDateTime.fromDate(new Date("2025-08-26T07:48:31.768Z")),
  }),
];
